import { CourseModule, ExamQuestion, UserProfile, ClassGroup } from './types';

// Real mock user profiles
export const MOCK_USER: UserProfile = {
  id: 'usr_01',
  name: 'Nguyễn Anh Minh',
  email: 'nguyenbao42013@gmail.com', // Active User Email from environment
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150',
  role: 'student',
  birthDate: '2005-08-15',
  schoolName: 'Hanoi University of Science and Technology',
  gradeClass: 'K68-CNTT',
  country: 'Vietnam',
  xp: 1450,
  level: 12,
  streakDays: 8,
  hoursStudied: 32.5,
  completionRate: 68,
  badges: [
    { id: 'b_01', title: 'Khởi đầu Đột phá', description: 'Hoàn thành bài học đầu tiên trong lộ trình IC3', icon: 'Award', rarity: 'Common', unlockedAt: '2026-06-10' },
    { id: 'b_02', title: 'Chiến binh Bất bại', description: 'Đạt chuỗi liên tiếp học tập 7 ngày', icon: 'Flame', rarity: 'Rare', unlockedAt: '2026-06-17' },
    { id: 'b_03', title: 'Vua Thao tác', description: 'Hoàn thành xuất sắc phần Key Applications (Word/Excel)', icon: 'Cpu', rarity: 'Epic', unlockedAt: '2026-06-15' },
  ],
  achievements: [
    { id: 'a_01', title: 'Chăm học cả tuần', description: 'Giữ chuỗi ngày học liên tiếp tối thiểu 7 ngày', currentValue: 8, targetValue: 7, completedAt: '2026-06-17' },
    { id: 'a_02', title: 'Vượt ải Thử thách', description: 'Điểm số thi thử IC3 đạt tối thiểu 750 điểm', currentValue: 820, targetValue: 700, completedAt: '2026-06-16' },
    { id: 'a_03', title: 'Thu hoạch Tri thức', description: 'Tích lũy tối rinh 2000 điểm XP trên hệ thống', currentValue: 1450, targetValue: 2000 },
  ],
};

// Realistic mock IC3 GS6 Courses
export const IC3_COURSES: CourseModule[] = [
  {
    id: 'm_cf',
    title: 'LEVEL 1: Kiến thức nền tảng (Computing Fundamentals)',
    code: 'IC3-GS6-LEVEL1',
    description: 'Tìm hiểu phần cứng máy tính, thiết bị ngoại vi, hệ điều hành hệ thống, ứng dụng phần mềm, cài đặt và sao lưu dữ liệu cơ bản.',
    progress: 0,
    color: 'emerald',
    lessons: [
      {
        id: 'cf_l1',
        title: 'Giới thiệu về Hệ sinh thái Máy tính',
        duration: '15:10',
        type: 'video',
        isCompleted: false,
        xpReward: 50,
      },
      {
        id: 'cf_l2',
        title: 'Hệ điều hành & Quản lý Tập tin hệ thống',
        duration: '12 trang',
        type: 'pdf',
        pdfTitle: 'Giao trinh OS vac Storage IC3 GS6.pdf',
        isCompleted: false,
        xpReward: 30,
      },
      {
        id: 'cf_l3',
        title: 'Flashcard Thuật ngữ Phần cứng & RAM/ROM',
        duration: '20 thẻ',
        type: 'flashcard',
        flashcards: [
          { front: 'RAM (Random Access Memory)', back: 'Bộ nhớ dữ liệu tạm thời, bị mất hoàn toàn dữ liệu khi điện nguồn máy tính bị ngắt.' },
          { front: 'ROM (Read Only Memory)', back: 'Bộ nhớ chỉ đọc chứa firmware khởi động hệ thống BIOS/UEFI, không mất dữ liệu.' },
          { front: 'SSD (Solid State Drive)', back: 'Ổ cứng thể rắn tốc độ cực cao, lưu trữ lâu dài dùng chip nhớ Flash thay cho phiến đĩa từ.' },
          { front: 'CPU (Central Processing Unit)', back: 'Bộ vi xử lý trung tâm, đóng vai trò đầu não thực thi các mã lệnh của phần mềm.' },
          { front: 'Operating System (Hệ điều hành)', back: 'Phần mềm nền tảng quản lý phần cứng và kết nối giữa người dùng cùng các app cài đặt.' },
        ],
        isCompleted: false,
        xpReward: 40,
      },
      {
        id: 'cf_l4',
        title: 'Quiz Ôn tập Quản lý thiết bị lưu trữ đám mây',
        duration: '5 câu hỏi',
        type: 'quiz',
        quizQuestions: [],
        isCompleted: false,
        xpReward: 60,
      },
    ],
  },
  {
    id: 'm_ka',
    title: 'LEVEL 2: Các ứng dụng chủ chốt (Key Applications)',
    code: 'IC3-GS6-LEVEL2',
    description: 'Thao tác nâng cao trên tài liệu Microsoft Word, định dạng bảng tính thông minh Excel, thiết kế thuyết trình PowerPoint hiện đại.',
    progress: 0,
    color: 'blue',
    lessons: [
      {
        id: 'ka_l1',
        title: 'Microsoft Word: Định dạng Bố cục, Thư viện & Header/Footer',
        duration: '18:45',
        type: 'video',
        isCompleted: false,
        xpReward: 50,
      },
      {
        id: 'ka_l2',
        title: 'Microsoft Excel: Công thức cơ bản (SUM, AVERAGE, IF, VLOOKUP)',
        duration: '15 trang',
        type: 'pdf',
        pdfTitle: 'Huong dan Excel Formulas nang cao IC3.pdf',
        isCompleted: false,
        xpReward: 35,
      },
      {
        id: 'ka_l3',
        title: 'Flashcard Thao tác thiết kế Slide PowerPoint',
        duration: '15 thẻ',
        type: 'flashcard',
        flashcards: [
          { front: 'Slide Master', back: 'Slide gốc điều khiển giao diện thiết kế, phông chữ, bố cục của tất cả slide con trong file.' },
          { front: 'Transition', back: 'Hiệu ứng chuyển đổi mỹ thuật GIỮA các slide khi trình diễn.' },
          { front: 'Animation', back: 'Hiệu ứng hoạt họa dành riêng cho các thành phần con BÊN TRONG một slide.' },
          { front: 'Presenter View', back: 'Chế độ hiển thị dành riêng cho người nói, cho phép đọc slide notes và xem slide kế tiếp.' },
        ],
        isCompleted: false,
        xpReward: 40,
      },
      {
        id: 'ka_l4',
        title: 'Bài tập thực hành Excel lọc dữ liệu nâng cao',
        duration: 'Tác vụ thực hành',
        type: 'practice',
        isCompleted: false,
        xpReward: 100,
      },
    ],
  },
  {
    id: 'm_lo',
    title: 'LEVEL 3: Cuộc sống trực tuyến (Living Online)',
    code: 'IC3-GS6-LEVEL3',
    description: 'Kỹ năng mạng internet, bảo mật email cá nhân, bảo mật dữ liệu, tìm kiếm thông minh, mạng xã hội và kỹ năng công dân số văn minh.',
    progress: 0,
    color: 'purple',
    lessons: [
      {
        id: 'lo_l1',
        title: 'Kỹ năng giao tiếp số & Thư điện tử chuyên nghiệp',
        duration: '14:20',
        type: 'video',
        isCompleted: false,
        xpReward: 50,
      },
      {
        id: 'lo_l2',
        title: 'Cẩm nang Bảo mật mạng, Firewall & Chống lừa đảo qua mạng',
        duration: '22 trang',
        type: 'pdf',
        pdfTitle: 'Cam nang an ninh mang IC3 GS6.pdf',
        isCompleted: false,
        xpReward: 30,
      },
      {
        id: 'lo_l3',
        title: 'Flashcard An toàn Công dân số',
        duration: '10 thẻ',
        type: 'flashcard',
        flashcards: [
          { front: 'Phishing', back: 'Hình thức tấn công giả mạo email hoặc microsite uy tín để lừa đảo đoạt mật khẩu, tài khoản bank.' },
          { front: 'Trojan Horse', back: 'Mã độc ngụy trang dưới dạng phần mềm hợp pháp để xâm nhập phá hoại máy thu thập thông tin.' },
          { front: 'MFA/2FA (Xác thực hai yếu tố)', back: 'Cơ chế kích hoạt thêm mã OTP gửi về Mobile hoặc App Authenticator để tăng bảo mật khóa.' },
          { front: 'Digital Footprint (Vết chân số)', back: 'Tất cả các vết tích lưu lại trên Internet khi bạn lướt web, gửi email, đăng tin mạng xã hội.' },
        ],
        isCompleted: false,
        xpReward: 40,
      },
    ],
  },
];

// Rich list of exam simulation questions - complete & high fidelity
export const MOCK_EXAM_QUESTIONS: ExamQuestion[] = [
  {
    id: 'q_01',
    type: 'MULTIPLE_CHOICE',
    category: 'Computing Fundamentals',
    subCategory: 'Hệ điều hành & Quản lý tập tin',
    questionText: 'Khi bạn xóa một tệp tin trên ổ đĩa cứng hoặc bộ nhớ di động ngoài (e.g. thẻ nhớ USB) trong hệ điều hành Windows 11, hành vi nào sau đây xảy ra chính xác?',
    options: [
      'A. Tệp tin trên USB bị xóa vĩnh viễn ngay lập tức, tệp trên ổ đĩa cứng chuyển vào Recycle Bin.',
      'B. Cả hai tệp tin đều được chuyển vào Recycle Bin để khôi phục khi cần thiết.',
      'C. Cả hai tệp tin đều bị xóa vĩnh viễn trực tiếp không qua lưu trữ tạm.',
      'D. Tệp tin trên ổ cứng bị xóa vĩnh viễn, tệp trên USB được gom vào Recycle Bin.',
    ],
    correctAnswer: 'A. Tệp tin trên USB bị xóa vĩnh viễn ngay lập tức, tệp trên ổ đĩa cứng chuyển vào Recycle Bin.',
    explanation: 'Trong Windows, mặc định các tập tin bị xóa từ các thiết bị lưu trữ di động ngoài (Removable Storage) như thẻ nhớ hoặc USB sẽ bị xóa hoàn toàn khỏi thiết bị ngay lập tức mà không đi qua sọt rác (Recycle Bin), trong khi các tệp xoá trên phân vùng ổ đĩa cứng nội bộ sẽ được chuyển vào Recycle Bin.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 45,
  },
  {
    id: 'q_02',
    type: 'TRUE_FALSE',
    category: 'Computing Fundamentals',
    subCategory: 'Bộ nhớ lưu trữ',
    questionText: 'Bản chất của RAM là bộ nhớ khả biến (volatile), dữ liệu được lưu trữ tạm thời bới các tụ điện sạc điện và sẽ bị giải phóng sạch sẽ khi thiết bị mất dòng điện nguồn cung cấp.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'RAM là bộ nhớ truy cập ngẫu nhiên có tính khả biến. Khi máy tính tắt nguồn hoặc mất điện đột ngột, toàn bộ cấu trúc sơ đồ điện tích nạp bên trong bộ nhớ tụ biến mất, dẫn đến việc giải phóng và xóa sách toàn bộ thông số đang được chạy.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_03',
    type: 'MATCHING',
    category: 'Key Applications',
    subCategory: 'Phần mềm Word & Excel',
    questionText: 'Nối các phím tắt phổ biến trong Microsoft Office với mục đích tương ứng của chúng:',
    matchingPairs: [
      { left: 'F4', right: 'Khóa tham chiếu tuyệt đối dòng/cột ô trong Excel hoặc lặp lại thao tác trước đó' },
      { left: 'F12', right: 'Mở trực tiếp hộp thoại Save As để lưu tệp tin dưới tên hoặc định dạng khác' },
      { left: 'Ctrl + F9', right: 'Chèn ký tự ngoặc nhọn trống { } để tạo trường / field codes trong Word' },
      { left: 'Alt + F4', right: 'Đóng hoàn toàn ứng dụng hoặc cửa sổ làm việc hiện hành' },
    ],
    correctAnswer: {
      'F4': 'Khóa tham chiếu tuyệt đối dòng/cột ô trong Excel hoặc lặp lại thao tác trước đó',
      'F12': 'Mở trực tiếp hộp thoại Save As để lưu tệp tin dưới tên hoặc định dạng khác',
      'Ctrl + F9': 'Chèn ký tự ngoặc nhọn trống { } để tạo trường / field codes trong Word',
      'Alt + F4': 'Đóng hoàn toàn ứng dụng hoặc cửa sổ làm việc hiện hành',
    },
    explanation: 'F4 kích hoạt khóa địa chỉ tuyệt đối (e.g. $A$1) trong Excel. F12 xuất hộp thoại Save As. Ctrl + F9 tạo khối trường ẩn trong Word và Alt + F4 là phím thoát trực tiếp ứng dụng Windows.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 60,
  },
  {
    id: 'q_04',
    type: 'HOTSPOT',
    category: 'Key Applications',
    subCategory: 'Microsoft Excel Ribbon Interface',
    questionText: 'Trong giao diện dải băng Ribbon của Excel dưới đây, đâu là khu vực chứa "Formula Bar" (Thanh công thức) để sửa đổi nội dung và kiểm tra cấu trúc cú pháp của ô? Hãy tick trực tiếp vào đúng vị trí của vùng thanh công thức.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600',
    hotspots: [
      { id: 'ribbon_tabs', x: 200, y: 35, label: 'Thanh tab ribbon (Home, Insert, Formulas...)' },
      { id: 'formula_bar_correct', x: 250, y: 110, label: 'Thanh công thức Formula Bar (Xấp xỉ phía trên lưới ô)' },
      { id: 'cell_grid', x: 300, y: 220, label: 'Lưới ô trang tính (A1, B2...)' },
    ],
    correctAnswer: 'formula_bar_correct',
    explanation: 'Thanh công thức (Formula Bar) nằm ngay bên dưới dải Ribbon chính và phía trên lưới trang tính, bắt đầu bằng biểu tượng fx, giúp người sử dụng nhập và quản lý công thức tính toán tiện lợi.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 50,
  },
  {
    id: 'q_05',
    type: 'FILL_BLANK',
    category: 'Living Online',
    subCategory: 'Giao thức bảo mật Web',
    questionText: 'Trong giao thức URL của trang web bảo mật cao, ký tự "S" trong cụm "HTTPS" là từ viết tắt của từ tiếng Anh nào? (Nhập chính xác 1 từ duy nhất, chữ hoa hay thường đều được chấp nhận)',
    correctAnswer: 'secure',
    explanation: 'HTTPS là viết tắt của "Hypertext Transfer Protocol Secure", là giao thức truyền tải siêu văn bản an toàn nhờ sử dụng chứng chỉ mã hóa dữ liệu cơ bản SSL/TLS.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_06',
    type: 'ORDERING',
    category: 'Living Online',
    subCategory: 'Quy trình giao tiếp số bảo mật',
    questionText: 'Sắp xếp theo thứ tự chuẩn các bước thiết lập cơ chế xác thực hai cấu phần (MFA/2FA) để khóa bảo vệ hòm thư cá nhân trước các cuộc tấn công chiếm quyền:',
    options: [
      'A. Tải xuống và cài đặt app Authenticator (như Google Authenticator) về thiết bị di động.',
      'B. Truy cập phần thiết lập Security (Bảo mật tài khoản), chọn kích hoạt 2-Step Verification.',
      'C. Dùng camera điện thoại của bạn quét trực tiếp mã QR được hiển thị trên màn hình máy tính.',
      'D. Nhập mã OTP gồm 6 chữ số sinh ra từ app điện thoại ngược lại trang web để xác thực kết nối và lưu các mã khôi phục khẩn cấp.',
    ],
    correctAnswer: ['A. Tải xuống và cài đặt app Authenticator (như Google Authenticator) về thiết bị di động.', 'B. Truy cập phần thiết lập Security (Bảo mật tài khoản), chọn kích hoạt 2-Step Verification.', 'C. Dùng camera điện thoại của bạn quét trực tiếp mã QR được hiển thị trên màn hình máy tính.', 'D. Nhập mã OTP gồm 6 chữ số sinh ra từ app điện thoại ngược lại trang web để xác thực kết nối và lưu các mã khôi phục khẩn cấp.'],
    explanation: 'Quy trình chuẩn bao gồm: Chuẩn bị app -> Chọn kích hoạt trên tài khoản -> Liên kết tài khoản bằng mã QR -> Xác thực lại bằng OTP hiện thời và lưu trữ mã khôi phục (Backup Codes).',
    difficulty: 'Hard',
    recommendedTimeSeconds: 70,
  },
  {
    id: 'q_07',
    type: 'MULTIPLE_RESPONSE',
    category: 'Computing Fundamentals',
    subCategory: 'Tải và Cài đặt Phần mềm thích ứng',
    questionText: 'Những lý do cốt lõi nào khiến việc tải xuống và cài đặt phần mềm bẻ khóa (cracked software) mang lại hiểm họa rất lớn cho hệ thống máy tính doanh nghiệp? (Chọn 2 đáp án tốt nhất)',
    options: [
      'A. Có nguy cơ rất cao bị cài cắm mã độc gián điệp, Trojan, Ransomware làm tê liệt rò rỉ dữ liệu.',
      'B. Phần mềm không nhận được cập nhật vá lỗi bảo mật định kỳ tự động từ nhà phát triển.',
      'C. Phần mềm crack luôn làm màn hình máy tính bị giảm độ phân giải xuống mức thấp nhất.',
      'D. Microsoft sẽ thu hồi hoàn toàn giấy phép bản quyền của hệ điều hành Windows gốc tức thời.',
    ],
    correctAnswer: [
      'A. Có nguy cơ rất cao bị cài cắm mã độc gián điệp, Trojan, Ransomware làm tê liệt rò rỉ dữ liệu.',
      'B. Phần mềm không nhận được cập nhật vá lỗi bảo mật định kỳ tự động từ nhà phát triển.',
    ],
    explanation: 'Phần mềm crack thường bị các lập trình viên mũ đen sửa mã nguồn để nhúng kèm trojan ăn cắp cookie, mật khẩu, và do bị ngắt liên kết đến máy chủ chính thức nên nó không thể cập nhật các bản sửa lỗi, tạo ra các lỗ hổng zero-day lớn.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 60,
  },
  {
    id: 'q_08',
    type: 'MULTIPLE_CHOICE',
    category: 'Computing Fundamentals',
    subCategory: 'Phần cứng máy tính',
    questionText: 'Thiết bị hay linh kiện điện tử nào sau đây phụ trách trực tiếp việc thực hiện các phép tính số học và phép toán logic chính của hệ thống máy tính?',
    options: [
      'A. Bộ nhớ đệm RAM',
      'B. Bộ xử lý trung tâm CPU',
      'C. Ổ đĩa cứng thể rắn SSD',
      'D. Bộ xử lý đồ họa tích hợp GPU',
    ],
    correctAnswer: 'B. Bộ xử lý trung tâm CPU',
    explanation: 'CPU (Central Processing Unit) chứa khối tính toán ALU có vai trò là đầu não xử lý toàn bộ các tập lệnh số học và logic của hệ điều hành.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_09',
    type: 'TRUE_FALSE',
    category: 'Computing Fundamentals',
    subCategory: 'Hệ thống tập tin',
    questionText: 'Hệ thống tập tin NTFS hỗ trợ khả năng quản lý phân quyền bảo mật (Security Permissions) và nén dữ liệu tốt hơn hẳn so với hệ thống cũ FAT32 trên Windows.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'NTFS cung cấp các cơ chế phân quyền bảo mật cấp độ người dùng, mã hóa tệp tin EFS và hỗ trợ các tập tin lớn hơn 4GB vượt trội hơn FAT32.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_10',
    type: 'MULTIPLE_CHOICE',
    category: 'Computing Fundamentals',
    subCategory: 'Cổng kết nối',
    questionText: 'Chuẩn kết nối ngoại vi nào sau đây hỗ trợ truyền tải cùng lúc cả tín hiệu video (hình ảnh) chất lượng tốt và âm thanh đa kênh số?',
    options: [
      'A. VGA',
      'B. DVI',
      'C. HDMI',
      'D. Jack âm thanh 3.5mm',
    ],
    correctAnswer: 'C. HDMI',
    explanation: 'HDMI (High-Definition Multimedia Interface) cho phép truyền phát tín hiệu số đồng bộ hóa cả hình ảnh lẫn âm thanh trên cùng một sợi cáp duy nhất.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 40,
  },
  {
    id: 'q_11',
    type: 'FILL_BLANK',
    category: 'Computing Fundamentals',
    subCategory: 'Số liệu đo lường',
    questionText: 'Theo chuẩn nhị phân truyền thống (Base 2), có bao nhiêu Kilobytes (KB) tương đương với 1 Megabyte (MB)? (Chỉ điền ký tự số nguyên dương)',
    correctAnswer: '1024',
    explanation: 'Công thức chuyển đổi chuẩn nhị phân công nghệ thông tin là 1 MB = 1024 KB.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_12',
    type: 'MULTIPLE_RESPONSE',
    category: 'Computing Fundamentals',
    subCategory: 'Danh mục bộ nhớ',
    questionText: 'Những thiết bị hay thành phần lưu trữ nào dưới đây được xếp vào nhóm bộ nhớ không biến đổi (non-volatile)? (Chọn 2 đáp án)',
    options: [
      'A. Bộ nhớ đệm Cache L1, L2 bên trong CPU',
      'B. Ổ đĩa cứng thể rắn SSD',
      'C. Thanh bộ nhớ truy cập ngẫu nhiên RAM',
      'D. Bộ nhớ dạng Flash USB di động',
    ],
    correctAnswer: [
      'B. Ổ đĩa cứng thể rắn SSD',
      'D. Flash USB di động',
    ],
    explanation: 'SSD và USB flash lưu giữ dữ liệu an toàn kể cả khi thiết bị hoàn toàn ngắt nguồn cung cấp.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 50,
  },
  {
    id: 'q_13',
    type: 'MULTIPLE_CHOICE',
    category: 'Computing Fundamentals',
    subCategory: 'Xử lý sự cố',
    questionText: 'Khi bấm khởi động máy tính, quạt hút nguồn chạy bình thường nhưng màn hình không có tín hiệu biểu thị và bo mạch phát bíp bíp liên tục. Đâu là nguyên nhân cơ bản đáng ngờ nhất?',
    options: [
      'A. CPU bị quá nhiệt do keo tản nhiệt bị khô.',
      'B. Lỏng lẻo chân cắm, bám bụi bẩn hoặc lỗi thanh bộ nhớ RAM.',
      'C. Ổ cứng HDD bị phân mảnh đầu đọc cơ học.',
      'D. Trình điều khiển chuột USB bị gỡ bỏ đột ngột.',
    ],
    correctAnswer: 'B. Lỏng lẻo chân cắm, bám bụi bẩn hoặc lỗi thanh bộ nhớ RAM.',
    explanation: 'Mainboard phát tín hiệu còi bíp chuỗi dài ngắt quãng báo hiệu máy tính chưa nhận diện được chân tiếp xúc RAM phù hợp.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 45,
  },
  {
    id: 'q_14',
    type: 'TRUE_FALSE',
    category: 'Computing Fundamentals',
    subCategory: 'Phần mềm',
    questionText: 'Trình điều khiển thiết bị (Device Driver) là một loại phần mềm ứng dụng chuyên nghiệp, phục vụ trực tiếp cho mục đích văn bản hoặc vẽ đồ họa của người sử dụng mạng.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai',
    explanation: 'Device Driver thuộc phân loại phần mềm hệ thống, làm cầu nối giúp hệ điều hành điều khiển và đồng bộ phần cứng, không phải phần mềm ứng dụng cho người dùng cuối.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_15',
    type: 'MULTIPLE_CHOICE',
    category: 'Computing Fundamentals',
    subCategory: 'Sao lưu bảo mật',
    questionText: 'Phương pháp sao lưu dữ liệu nào chỉ thực hiện thao tác sao chép lưu giữ các tập tin có thay đổi kể từ lần sao lưu đầy đủ gần đây nhất?',
    options: [
      'A. Incremental Backup (Sao lưu gia tăng)',
      'B. Differential Backup (Sao lưu khác biệt)',
      'C. Mirror Backup (Sao lưu gương soi)',
      'D. Chép đè trực tiếp (Overwrite)',
    ],
    correctAnswer: 'B. Differential Backup (Sao lưu khác biệt)',
    explanation: 'Differential Backup lưu trữ những phần thay đổi tích lũy so với bản Full gần nhất, giúp kiểm soát khôi phục ngắn gọn hơn.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 50,
  },
  {
    id: 'q_16',
    type: 'MATCHING',
    category: 'Computing Fundamentals',
    subCategory: 'Hệ máy tính',
    questionText: 'Nối phân loại kiến trúc máy tính với vai trò cốt lõi phù hợp nhất:',
    matchingPairs: [
      { left: 'Mainframe', right: 'Xử lý hàng triệu giao dịch khối lượng lớn của mạng ngân hàng' },
      { left: 'Server', right: 'Quản trị phân phối dịch vụ mạng và chia sẻ dữ liệu chung' },
      { left: 'Workstation', right: 'Chuyên dụng vẽ kỹ thuật kiến trúc hoặc dựng kỹ xảo phim' },
      { left: 'Embedded System', right: 'Tích hợp điều khiển mạch quản lý thông minh của đồ gia dụng' },
    ],
    correctAnswer: {
      'Mainframe': 'Xử lý hàng triệu giao dịch khối lượng lớn của mạng ngân hàng',
      'Server': 'Quản trị phân phối dịch vụ mạng và chia sẻ dữ liệu chung',
      'Workstation': 'Chuyên dụng vẽ kỹ thuật kiến trúc hoặc dựng kỹ xảo phim',
      'Embedded System': 'Tích hợp điều khiển mạch quản lý thông minh của đồ gia dụng',
    },
    explanation: 'Mainframe xử lý giao dịch quy mô khổng lồ. Server cấp tài nguyên. Workstation chuyên sâu đồ họa. Embedded là hệ thống nhúng điều khiển tự động.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 60,
  },
  {
    id: 'q_17',
    type: 'ORDERING',
    category: 'Computing Fundamentals',
    subCategory: 'Quy trình Boot',
    questionText: 'Sắp xếp quy trình khởi động tuần tự của hệ thống máy tính kể từ lúc tắt nguồn vật lý:',
    options: [
      'A. Nhấn nút nguồn vật lý cấp dòng điện kích hoạt bo mạch chủ.',
      'B. Hệ chương trình BIOS/UEFI chạy rà soát phần cứng tự kiểm tra POST.',
      'C. BIOS nạp Master Boot Record (MBR) định vị phân vùng hoạt động để tải bootloader.',
      'D. Kernel của hệ điều hành được nạp vào bộ nhớ RAM và chạy giao diện đăng nhập.',
    ],
    correctAnswer: [
      'A. Nhấn nút nguồn vật lý cấp dòng điện kích hoạt bo mạch chủ.',
      'B. Hệ chương trình BIOS/UEFI chạy rà soát phần cứng tự kiểm tra POST.',
      'C. BIOS nạp Master Boot Record (MBR) định vị phân vùng hoạt động để tải bootloader.',
      'D. Kernel của hệ điều hành được nạp vào bộ nhớ RAM và chạy giao diện đăng nhập.',
    ],
    explanation: 'Trình tự cơ học: Điện nguồn -> POST kiểm tra phần cứng -> Đọc bản ghi MBR nạp bootloader -> Load nhân điều hành khởi chạy.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 65,
  },
  {
    id: 'q_18',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Trình soạn thảo MS Word',
    questionText: 'Để điều chỉnh khoảng cách (giãn dòng) của các dòng chữ trong một đoạn văn bản MS Word chuẩn mực, bạn sử dụng lệnh nào?',
    options: [
      'A. Line and Paragraph Spacing',
      'B. Margins setup',
      'C. Orientation layout',
      'D. Columns division',
    ],
    correctAnswer: 'A. Line and Paragraph Spacing',
    explanation: 'Nút biểu tượng giãn dòng Line and Paragraph Spacing nằm trên tab Home, nhóm Paragraph thiết lập các chỉ số giãn dòng linh hoạt.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_19',
    type: 'TRUE_FALSE',
    category: 'Key Applications',
    subCategory: 'Cấu trúc tài liệu',
    questionText: 'Phần Header (tiêu đề đầu) và Footer (tiêu đề chân) sau khi soạn sẽ tự động kế thừa lặp lại trên mọi trang của cùng một vùng tài liệu (Section).',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'Header và Footer lưu giữ định dạng chung cố định cho từng trang nằm trong cùng một phân vùng để thống nhất bố cục in ấn.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_20',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Trang tính MS Excel',
    questionText: 'Cú pháp hàm nào sau đây hoàn toàn đúng quy chuẩn của MS Excel để tính trung bình số học từ ô A1 đến A5?',
    options: [
      'A. =AVERAGE(A1:A5)',
      'B. =MEAN(A1:A5)',
      'C. =AVGERAGE(A1-A5)',
      'D. =SUM(A1:A5)/5',
    ],
    correctAnswer: 'A. =AVERAGE(A1:A5)',
    explanation: 'Hàm AVERAGE nhận các đối số là vùng phân dải bằng dấu hai chấm để giải trình tích hữu dụng tối đa.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_21',
    type: 'FILL_BLANK',
    category: 'Key Applications',
    subCategory: 'Hàm tính toán',
    questionText: 'Gõ tên hàm viết liền bằng tiếng Anh (chữ hoa) chuyên dùng để tính tổng các ô trong một phạm vi thỏa mãn một điều kiện cho trước:',
    correctAnswer: 'SUMIF',
    explanation: 'Hàm SUMIF kết hợp kiểm định điều kiện logic và tính tổng phạm vi vùng số thích hợp.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 25,
  },
  {
    id: 'q_22',
    type: 'MULTIPLE_RESPONSE',
    category: 'Key Applications',
    subCategory: 'Trình chiếu PPT',
    questionText: 'Những nhóm hiệu ứng thành phần hoạt họa nào sau đây được hỗ trợ mặc định cho đối tượng hình ảnh hay văn bản trong MS PowerPoint? (Chọn 2 đáp án)',
    options: [
      'A. Entrance Effects (Hiệu ứng khi đối tượng xuất hiện)',
      'B. Exit Effects (Hiệu ứng biến mất rũ bỏ)',
      'C. Auto-Align Effects (Hiệu ứng chỉnh thẳng hàng)',
      'D. Border Color Effects (Hiệu ứng thay đổi bề dày nét viền)',
    ],
    correctAnswer: [
      'A. Entrance Effects (Hiệu ứng khi đối tượng xuất hiện)',
      'B. Exit Effects (Hiệu ứng biến mất rũ bỏ)',
    ],
    explanation: 'Bốn nhóm hiệu ứng của slide: Entrance (Xuất hiện), Emphasis (Nhấn mạnh), Exit (Biến mất) và Motion Paths (Đường di chuyển).',
    difficulty: 'Medium',
    recommendedTimeSeconds: 40,
  },
  {
    id: 'q_23',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Lỗi giao diện Excel',
    questionText: 'Trong trang tính Excel, nếu bên trong một ô hiển thị chuỗi ký tự lỗi dạng "#####", hiện tượng này biểu hiện điều gì?',
    options: [
      'A. Công thức toán học tính toán chứa phép chia cho giá trị không.',
      'B. Độ rộng của cột đang quá hẹp để có thể hiển thị trọn vẹn số hoặc ngày tháng.',
      'C. Nhập sai tên hàm phân dải của bảng dữ liệu tính.',
      'D. Tham chiếu ô không xác định được vị trí dữ liệu.',
    ],
    correctAnswer: 'B. Độ rộng của cột đang quá hẹp để có thể hiển thị trọn vẹn số hoặc ngày tháng.',
    explanation: 'Lỗi hiển thị hàng rào ##### chỉ ra rằng giá trị dạng số hoặc thời gian bị khuất tầm hiển thị. Cần kéo giãn kích thước cột.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_24',
    type: 'TRUE_FALSE',
    category: 'Key Applications',
    subCategory: 'Soạn thảo nâng cao',
    questionText: 'Chức năng Track Changes trong Microsoft Word được xây dựng nhằm tự động dịch đổi mọi nội dung văn bản từ ngôn ngữ tiếng Việt sang tiếng Anh tức thời.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai',
    explanation: 'Track Changes phục vụ giám sát và ghi lại vết chỉnh sửa nội dung, thêm thắt, xóa bỏ để nhiều người dùng cộng tác duyệt bài, không phải tính năng dịch thuật.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_25',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Phím tắt ứng dụng',
    questionText: 'Tổ hợp phím tắt tiêu chuẩn nào hỗ trợ bạn ngắt trang thủ công bắt buộc tại vị trí con trỏ hiện hành trong MS Word?',
    options: [
      'A. Ctrl + Enter',
      'B. Shift + Enter',
      'C. Alt + Enter',
      'D. Ctrl + Shift + Space',
    ],
    correctAnswer: 'A. Ctrl + Enter',
    explanation: 'Ctrl+Enter tạo lệnh ngắt trang cứng (Page Break), lập tức đẩy con trỏ soạn thảo sang đỉnh đầu của trang kế tiếp.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_26',
    type: 'MATCHING',
    category: 'Key Applications',
    subCategory: 'Danh mục hàm tính',
    questionText: 'Nối các hàm trang tính MS Excel với mô tả vai trò mục đích tính toán của chúng:',
    matchingPairs: [
      { left: 'VLOOKUP', right: 'Tìm giá trị trên cột dọc rồi tham chiếu ngang hàng bảng chỉ định' },
      { left: 'COUNTIF', right: 'Đếm số lượng ô có chứa giá trị thỏa điều kiện chọn' },
      { left: 'IF', right: 'Kiểm định biểu thức điều kiện để phân nhánh trả kết quả phù hợp' },
      { left: 'PMT', right: 'Tính giá trị tiền chi trả định kỳ của các khoản trả góp lãi suất cố định' },
    ],
    correctAnswer: {
      'VLOOKUP': 'Tìm giá trị trên cột dọc rồi tham chiếu ngang hàng bảng chỉ định',
      'COUNTIF': 'Đếm số lượng ô có chứa giá trị thỏa điều kiện chọn',
      'IF': 'Kiểm định biểu thức điều kiện để phân nhánh trả kết quả phù hợp',
      'PMT': 'Tính giá trị tiền chi trả định kỳ của các khoản trả góp lãi suất cố định',
    },
    explanation: 'VLOOKUP là dò tìm cột. COUNTIF đếm có điều kiện. IF kiểm thử nhánh logic. PMT tính gốc lãi trả nợ kỳ hạn.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 65,
  },
  {
    id: 'q_27',
    type: 'ORDERING',
    category: 'Key Applications',
    subCategory: 'Trộn thư Mail Merge',
    questionText: 'Sắp xếp theo quy trình chuẩn hóa các thao tác thực hiện tiện ích trộn thư mời hàng loạt (Mail Merge) trên MS Word:',
    options: [
      'A. Chuẩn bị bảng lưu trữ và sắp xếp dữ liệu thông tin khách hàng (như Excel).',
      'B. Soạn sẵn tệp tin văn bản mẫu hoặc hòm khung mẫu cho thư mời.',
      'C. Kết nối văn bản mẫu với bảng nguồn dữ liệu khách hàng bên ngoài.',
      'D. Chèn các trường dữ liệu tự động thay thế và tiến hành xuất in hàng loạt (Finish & Merge).',
    ],
    correctAnswer: [
      'A. Chuẩn bị bảng lưu trữ và sắp xếp dữ liệu thông tin khách hàng (như Excel).',
      'B. Soạn sẵn tệp tin văn bản mẫu hoặc hòm khung mẫu cho thư mời.',
      'C. Kết nối văn bản mẫu với bảng nguồn dữ liệu khách hàng bên ngoài.',
      'D. Chèn các trường dữ liệu tự động thay thế và tiến hành xuất in hàng loạt (Finish & Merge).',
    ],
    explanation: 'Chu trình hoàn thiện: Tạo danh sách nguồn -> Soạn mẫu tài liệu -> Kết nối liên kết tệp mẫu -> Ánh xạ điền trường liên tiếp.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 70,
  },
  {
    id: 'q_28',
    type: 'MULTIPLE_RESPONSE',
    category: 'Key Applications',
    subCategory: 'Quy tắc công thức',
    questionText: 'Những ký tự hay cụm toán tử nào sau đây có thể dùng hợp quy làm khởi nguồn để dòng lệnh tính toán Excel nhận diện bắt đầu một công thức? (Chọn 2 đáp án)',
    options: [
      'A. Dấu bằng (=)',
      'B. Dấu cộng (+)',
      'C. Dấu hai chấm (:)',
      'D. Dấu hỏi chấm (?)',
    ],
    correctAnswer: [
      'A. Dấu bằng (=)',
      'B. Dấu cộng (+)',
    ],
    explanation: 'Excel mặc định kích hoạt diễn giải công thức số tính bằng cách bắt đầu với dấu bằng, tuy nhiên dấu cộng (+) hoặc dấu trừ (-) cũng có thể tự động hiểu tương tự.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 40,
  },
  {
    id: 'q_29',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'PowerPoint quản lý',
    questionText: 'Chế độ xem (View) nào trong MS PowerPoint ưu việt nhất cho việc hiển thị thu nhỏ hàng loạt các slide, giúp cấu trúc và sắp xếp lại tài liệu một cách gọn gàng?',
    options: [
      'A. Normal View',
      'B. Slide Sorter View',
      'C. Reading View',
      'D. Outline View',
    ],
    correctAnswer: 'B. Slide Sorter View',
    explanation: 'Slide Sorter hiển thị mạng lưới ma trận các trang chiếu cho phép kéo quẹt đổi thứ tự thuận tiện nhất.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_30',
    type: 'TRUE_FALSE',
    category: 'Key Applications',
    subCategory: 'Tính chất ô',
    questionText: 'Đặc trưng của địa chỉ ô tham chiếu tương đối (e.g. B2) là sẽ tự động tịnh tiến lệch hàng/cột tương ứng khi bạn sao chép kéo công thức sang các vị trí khác.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'Địa chỉ tương đối biến thiên linh động bám đuổi theo logic vị trí mới để bảo đảm liên hệ dữ liệu nối đuôi.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_31',
    type: 'FILL_BLANK',
    category: 'Key Applications',
    subCategory: 'Trình chiếu nhanh',
    questionText: 'Học sinh hãy gõ ký hiệu phím tắt (gồm ký tự chữ và số viết liền, ví dụ F1, F2...) dùng để chạy trình chiếu khẩn cấp PowerPoint từ slide trang đầu tiên:',
    correctAnswer: 'F5',
    explanation: 'Phím F5 kích hoạt chế độ Fullscreen trình chiếu mặc định từ đầu. Shift+F5 trình chiếu từ slide đang chọn.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 20,
  },
  {
    id: 'q_32',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Cơ chế rà lỗi Excel',
    questionText: 'Hàm dò tìm VLOOKUP sẽ phản hồi dạng mã lỗi hiển thị nào nếu không lọc tìm thấy đúng kết quả hợp thông số khi dải dò cuối được thiết lập là tìm chính xác (FALSE / 0)?',
    options: [
      'A. #VALUE!',
      'B. #N/A',
      'C. #REF!',
      'D. #NAME?',
    ],
    correctAnswer: 'B. #N/A',
    explanation: '#N/A tượng trưng cho "Not Available", cảnh báo không phát hiện được mục mục tương xứng trong phạm vi kho dữ liệu.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 35,
  },
  {
    id: 'q_33',
    type: 'TRUE_FALSE',
    category: 'Key Applications',
    subCategory: 'Xử lý chuỗi thông tin',
    questionText: 'Trong MS Word, một chiếc bảng dữ liệu tích hợp (Table) không thể bị tháo rời để chuyển dịch thành khối văn bản thuần tự chữ (Plain Text) mà bắt buộc phải xóa hoàn toàn đi.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai',
    explanation: 'Tab Layout của Table Tools cung cấp trực tiếp tính năng Convert to Text để biến bảng thành văn bản thuần phân dải qua Tab, Comma...',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_34',
    type: 'MULTIPLE_CHOICE',
    category: 'Key Applications',
    subCategory: 'Kho lưu đám mây',
    questionText: 'Trong bộ ứng dụng Office và Microsoft 365, đâu là tên tiện ích chuyên dùng quản lý lưu trữ đồng bộ dữ liệu đám mây của máy tính người dùng?',
    options: [
      'A. OneDrive',
      'B. Google Drive',
      'C. iCloud Storage',
      'D. Dropbox Live',
    ],
    correctAnswer: 'A. OneDrive',
    explanation: 'OneDrive là giải pháp máy chủ đám mây gốc được đính kèm tích hợp chặt chẽ cùng các ứng dụng Office của Microsoft.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_35',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Địa chỉ mạng',
    questionText: 'Theo tiêu chuẩn cấu hình mạng toàn cầu, một địa chỉ mạng IPv4 truyền thống bao gồm tổng cộng bao nhiêu bit nhị phân chia thành 4 octet?',
    options: [
      'A. 16 bit',
      'B. 32 bit',
      'C. 64 bit',
      'D. 128 bit',
    ],
    correctAnswer: 'B. 32 bit',
    explanation: 'IPv4 cấu trúc gồm 32 bit nhị phân được chia làm 4 nhóm phân định bằng dấu chấm hiển thị (số thập phân, ví dụ: 192.168.1.1).',
    difficulty: 'Medium',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_36',
    type: 'TRUE_FALSE',
    category: 'Living Online',
    subCategory: 'Mã độc rủi ro',
    questionText: 'Mã độc tống tiền Ransomware là một hình thức phần mềm độc hại phong tỏa thiết bị, tự động mã hóa hàng loạt tài liệu của nạn nhân và đe dọa xóa sổ đòi người dùng trả tiền chuộc.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'Ransomware giữ làm con tin cấu trúc mã của file, tạo áp lực buộc thanh toán tài khoản ẩn danh để mua mật mã tháo gỡ cực kỳ nguy hiểm.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_37',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Gửi thư điện tử Email',
    questionText: 'Khi gửi thư Email chung nhóm, nếu bạn mong muốn bổ sung một người đồng nhận thư nhưng không để cho bất kỳ ai khác nhận ra sự tồn tại liên hệ của họ, bạn điền địa chỉ người đó vào trường nào?',
    options: [
      'A. To (Đến người nhận chính)',
      'B. Cc (Carbon Copy)',
      'C. Bcc (Blind Carbon Copy)',
      'D. Subject (Chủ đề thư)',
    ],
    correctAnswer: 'C. Bcc (Blind Carbon Copy)',
    explanation: 'Bcc (Gửi bản sao ẩn danh) ẩn danh sách email của người được điền tại đó đối với mọi tài khoản nhận thư khác.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 40,
  },
  {
    id: 'q_38',
    type: 'FILL_BLANK',
    category: 'Living Online',
    subCategory: 'Mạng Web phổ thông',
    questionText: 'Sử dụng cụm từ tiếng Việt phổ thông (2 từ, chữ thường viết liền phân tách bằng một dấu cách): Tên phần mềm chuyên dụng hỗ trợ việc tìm kiếm truy cập dữ liệu trang web trên mạng Internet là gì?',
    correctAnswer: 'trình duyệt',
    explanation: 'Những phần mềm như Chrome, Edge, Safari và Firefox được chung gọi là các Trình duyệt Web (Web Browser).',
    difficulty: 'Easy',
    recommendedTimeSeconds: 25,
  },
  {
    id: 'q_39',
    type: 'MULTIPLE_RESPONSE',
    category: 'Living Online',
    subCategory: 'Lừa đảo an ninh',
    questionText: 'Những dấu hiện cảnh báo đặc trưng nào hỗ trợ phát hiện các hành vi lừa đảo mạng qua Email mạo danh (Phishing)? (Chọn 2 đáp án)',
    options: [
      'A. Email người gửi chứa các lỗi lỗi nhỏ cố ý gần giống thương hiệu lớn (ví dụ: support@amz0n-shop.com).',
      'B. Nội dung thư đe dọa, bắt buộc thực hiện khẩn cấp việc xác thực cung cấp thông tin bí mật tài khoản.',
      'C. Thư điện tử kèm các file đính kèm định lý rõ ở dạng ảnh phong cảnh tiêu chuẩn .jpg.',
      'D. Email có chữ xác nhận danh tính kỹ thuật số của cơ quan cung cấp chứng thực uy tín.',
    ],
    correctAnswer: [
      'A. Email người gửi chứa các lỗi lỗi nhỏ cố ý gần giống thương hiệu lớn (ví dụ: support@amz0n-shop.com).',
      'B. Nội dung thư đe dọa, bắt buộc thực hiện khẩn cấp việc xác thực cung cấp thông tin bí mật tài khoản.',
    ],
    explanation: 'Thư lừa đảo thường gây áp lực tâm lý giả vờ mất tài khoản kết hợp tên miền giả mạo lắt léo.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 50,
  },
  {
    id: 'q_40',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Dịch vụ mạng',
    questionText: 'Hệ thống máy chủ dịch vụ cốt lõi nào phụ trách ánh xạ trực tiếp các tên miền trực quan (như vnexpress.net) thành địa chỉ IP vật lý tương thích?',
    options: [
      'A. Hệ máy DHCP',
      'B. Hệ thống phân giải DNS',
      'C. Máy chủ bảo mật FTP',
      'D. Cổng chuyển đổi NAT',
    ],
    correctAnswer: 'B. Hệ thống phân giải DNS',
    explanation: 'DNS (Domain Name System) chuyển đổi ngôn ngữ của con người (tên miền chữ) thành số hóa địa chỉ IP mạng máy tính giao thức.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_41',
    type: 'TRUE_FALSE',
    category: 'Living Online',
    subCategory: 'Dữ liệu web',
    questionText: 'Bản chất của các tệp Cookies là các chủng virus siêu vi tự động cài cắm sâu vào hệ điều hành nhằm sửa cấu trúc bảo mật lưu trữ máy tính.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Sai',
    explanation: 'Cookies chỉ là các tệp văn bản nhỏ chứa thông tin định cấu hình, lưu vết đăng nhập hoặc lịch sử lướt web vô hại do trình duyệt quản lý cho các trang web.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_42',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Giao ứng thái độ',
    questionText: 'Thuật ngữ tiếng Anh đặc trưng nào đại diện cho bộ quy tắc văn minh, thái độ tôn trọng và lễ nghi giao tiếp lịch thiệp giữa con người trên không gian mạng?',
    options: [
      'A. Cyber-law',
      'B. Netiquette (Lịch ứng mạng)',
      'C. Digital Footprint',
      'D. Fair Use (Sử dụng công bằng)',
    ],
    correctAnswer: 'B. Netiquette (Lịch ứng mạng)',
    explanation: 'Netiquette là ghép nối của Net và Etiquette, là quy tắc ứng xử phi văn bản thể hiện tầm văn hóa số khi tham gia diễn đàn mạng.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 35,
  },
  {
    id: 'q_43',
    type: 'MATCHING',
    category: 'Living Online',
    subCategory: 'Kiến trúc mạng',
    questionText: 'Ghép nối định danh thiết bị truyền thông mạng với đúng vai trò nền tảng gốc của mạng điện toán:',
    matchingPairs: [
      { left: 'Router', right: 'Điều hướng vận chuyển các gói dữ liệu thông suốt giữa các phân vùng mạng khác nhau' },
      { left: 'Switch', right: 'Kết nối mạng trực tiếp liên kết các máy tính trong phân vùng mạng LAN nội bộ' },
      { left: 'Modem', right: 'Khớp nối điều chế chuyển đổi bước sóng tín hiệu tương tự sang hệ tín hiệu số' },
      { left: 'Firewall', right: 'Sàng lọc kiểm duyệt dòng lưu lượng ra vào mạng tuân thủ chính sách bảo mật' },
    ],
    correctAnswer: {
      'Router': 'Điều hướng vận chuyển các gói dữ liệu thông suốt giữa các phân vùng mạng khác nhau',
      'Switch': 'Kết nối mạng trực tiếp liên kết các máy tính trong phân vùng mạng LAN nội bộ',
      'Modem': 'Khớp nối điều chế chuyển đổi bước sóng tín hiệu tương tự sang hệ tín hiệu số',
      'Firewall': 'Sàng lọc kiểm duyệt dòng lưu lượng ra vào mạng tuân thủ chính sách bảo mật',
    },
    explanation: 'Router làm định tuyến. Switch kết nội mạng trong. Modem phiên dịch sóng điện hạ tầng ISP. Firewall bảo vệ ngăn chặn lọc cổng.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 65,
  },
  {
    id: 'q_44',
    type: 'ORDERING',
    category: 'Living Online',
    subCategory: 'Sự cố mất kết nối',
    questionText: 'Sắp xếp quy trình khắc phục và chuẩn đoán sự cố mất kết nối mạng Internet nội bộ tại tư gia một cách khoa học nhất:',
    options: [
      'A. Rà soát dò tìm xem các thiết bị xung quanh khác có kết nối bình thường với trạm không.',
      'B. Tiến hành ngắt phích cắm nguồn điện Modem/Router trong khoảng 30 giây rồi đấu nối lại khởi động.',
      'C. Trực tiếp kiểm duyệt các giắc cắm, cáp LAN nguồn nối từ hộp mạng vào cổng Gateway thiết bị.',
      'D. Gọi liên hệ tổng đài kỹ thuật báo hỏng của nhà cung cấp băng rộng để kiểm tra hạ tầng dây cáp.',
    ],
    correctAnswer: [
      'A. Rà soát dò tìm xem các thiết bị xung quanh khác có kết nối bình thường với trạm không.',
      'B. Tiến hành ngắt phích cắm nguồn điện Modem/Router trong khoảng 30 giây rồi đấu nối lại khởi động.',
      'C. Trực tiếp kiểm duyệt các giắc cắm, cáp LAN nguồn nối từ hộp mạng vào cổng Gateway thiết bị.',
      'D. Gọi liên hệ tổng đài kỹ thuật báo hỏng của nhà cung cấp băng rộng để kiểm tra hạ tầng dây cáp.',
    ],
    explanation: 'Các bước lần lượt: Định vị diện rộng -> Khởi động lại thiết bị trung gian -> Xác thực vật lý cổng cắm cáp -> Trợ giúp kỹ thuật nhà mạng.',
    difficulty: 'Hard',
    recommendedTimeSeconds: 60,
  },
  {
    id: 'q_45',
    type: 'MULTIPLE_RESPONSE',
    category: 'Living Online',
    subCategory: 'Đạo luật sở hữu',
    questionText: 'Những đối tượng sáng tạo số nào dưới đây được bảo hộ mặc định trực tiếp của đạo luật Bản quyền (Copyright)? (Chọn 2 đáp án)',
    options: [
      'A. Mã nguồn một phần mềm phần mềm viết độc lập.',
      'B. Ý tưởng triết học hay lập luận lý thuyết chưa ghi chép lại.',
      'C. Một bản ghi nhạc do nghệ sĩ phối khí thu thanh.',
      'D. Công thức toán nhân chia số vô tỷ.',
    ],
    correctAnswer: [
      'A. Mã nguồn một phần mềm phần mềm viết độc lập.',
      'C. Một bản ghi nhạc do nghệ sĩ phối khí thu thanh.',
    ],
    explanation: 'Bản quyền bảo hộ hình thức thể hiện vật lý rõ ràng như tác phẩm ghi âm, chương trình code máy tính, không bảo hộ ý tưởng trừu tượng trong não bộ.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 50,
  },
  {
    id: 'q_46',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Mô hình đám mây',
    questionText: 'Dịch vụ phân phối ứng dụng thành phẩm trực tiếp qua trình duyệt web mạng (như Google Docs, Canva, Microsoft Office 365) thuộc mô hình dịch vụ đám mây nào?',
    options: [
      'A. IaaS (Hạ tầng dịch vụ)',
      'B. PaaS (Nền tảng dịch vụ)',
      'C. SaaS (Phần mềm dịch vụ)',
      'D. DaaS (Lưu trữ dữ liệu dịch vụ)',
    ],
    correctAnswer: 'C. SaaS (Phần mềm dịch vụ)',
    explanation: 'SaaS (Software as a Service) cung cấp ứng dụng hoàn chỉnh cho người dùng đầu cuối thông qua Internet mà không cần cài đặt nguồn phức tạp.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_47',
    type: 'TRUE_FALSE',
    category: 'Living Online',
    subCategory: 'Vết tích mạng',
    questionText: 'Dấu chân kỹ thuật số (Digital Footprint) là mọi dấu vết, thông tin bạn để lại cấu thành trong quá trình duyệt mạng và hoàn toàn không thể xóa sạch triệt để khỏi mạng máy chủ.',
    options: ['Đúng', 'Sai'],
    correctAnswer: 'Đúng',
    explanation: 'Digital Footprint bao gồm lịch sử tìm kiếm, bài đăng mảng xã hội... vốn được lưu trữ tại nhiều máy chủ trung gian không thể rút hoàn toàn.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_48',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Đường truyền an toàn',
    questionText: 'Giải pháp bảo mật mạng nào hỗ trợ thiết lập một đường ống mã hóa bảo vệ (Tunneling) lưu lượng kết nối thông tin của bạn khỏi những kẻ rình mò khi dùng mạng wifi công cộng?',
    options: [
      'A. VPN (Mạng riêng ảo)',
      'B. WPS',
      'C. VoIP truyền giọng nói',
      'D. Giao thức WPA3',
    ],
    correctAnswer: 'A. VPN (Mạng riêng ảo)',
    explanation: 'VPN (Virtual Private Network) mã hóa bảo vệ và chuyển tiếp địa chỉ IP thông qua các máy chủ an toàn nâng tầm bảo mật kết nối.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 30,
  },
  {
    id: 'q_49',
    type: 'FILL_BLANK',
    category: 'Living Online',
    subCategory: 'Toán tử tra cứu',
    questionText: 'Điền ký tự phân giới (ví dụ: gõ phím ký tự đại diện duy nhất) được dùng ôm trọn cụm từ khóa khi tìm kiếm Google để cưỡng bách trả về kết quả khớp chính xác 100%:',
    correctAnswer: '"',
    explanation: 'Dấu ngoặc kép "..." kẹp chặt cụm từ, bắt buộc Google lọc đúng trật tự từ vựng cụ thể.',
    difficulty: 'Easy',
    recommendedTimeSeconds: 20,
  },
  {
    id: 'q_50',
    type: 'MULTIPLE_CHOICE',
    category: 'Living Online',
    subCategory: 'Khẩn cấp hiểm họa',
    questionText: 'Khi phát giác thiết bị máy tính cá nhân bị tấn công đột nhập rầm rộ bởi mã độc phá hoại làm mất kiểm soát, hành vi sơ cứu an toàn đầu tiên cần làm là gì?',
    options: [
      'A. Lập tức tắt công tắc điện hoặc ngắt kết nối dây mạng cáp/WiFi vật lý của máy tính.',
      'B. Tiến hành cắm củ sao lưu ổ đĩa ngoài vào máy để lưu tài liệu.',
      'C. Cố gắng tải cài đặt một ứng dụng dọn rác dọn dẹp hệ điều hành.',
      'D. Làm theo các điều khoản yêu cầu cung cấp tài khoản để thoát virus.',
    ],
    correctAnswer: 'A. Lập tức tắt công tắc điện hoặc ngắt kết nối dây mạng cáp/WiFi vật lý của máy tính.',
    explanation: 'Phải cô lập máy lập tức để chặn malware lây lan nội bộ mạng cục bộ hoặc tải nạp thêm payload mới từ máy chủ C2 của tin tặc.',
    difficulty: 'Medium',
    recommendedTimeSeconds: 30,
  },
];

// Classes for Teacher dashboard
export const MOCK_TEACHER_CLASSES: ClassGroup[] = [
  {
    id: 'cls_01',
    name: 'Lớp Luyện thi IC3 - Khóa Cơ bản K68',
    code: 'IC3-K68-BASIC',
    teacherId: 'usr_teacher_01',
    studentCount: 28,
    averageScore: 745,
    students: [
      { id: 'stud_01', name: 'Nguyễn Anh Minh', email: 'nguyenbao42013@gmail.com', completedLessons: 12, avgExamScore: 820, predictedPassRate: 94, streakDays: 8, activityStatus: 'active' },
      { id: 'stud_02', name: 'Lê Hoàng Minh', email: 'hoangminh.le@student.vn', completedLessons: 9, avgExamScore: 710, predictedPassRate: 72, streakDays: 4, activityStatus: 'active' },
      { id: 'stud_03', name: 'Phạm Khánh Linh', email: 'linhpk.sh@gmail.com', completedLessons: 11, avgExamScore: 780, predictedPassRate: 88, streakDays: 5, activityStatus: 'active' },
      { id: 'stud_04', name: 'Trần Tuấn Kiệt', email: 'kiettrantr@outlook.com', completedLessons: 3, avgExamScore: 520, predictedPassRate: 35, streakDays: 0, activityStatus: 'at_risk' },
      { id: 'stud_05', name: 'Vũ Hải Đăng', email: 'dangvh@fpt.edu.vn', completedLessons: 13, avgExamScore: 860, predictedPassRate: 98, streakDays: 12, activityStatus: 'active' },
      { id: 'stud_06', name: 'Nguyễn Bích Phương', email: 'phuongnb@outlook.com', completedLessons: 5, avgExamScore: 590, predictedPassRate: 48, streakDays: 1, activityStatus: 'inactive' },
    ],
    assignments: [
      { id: 'asgn_01', title: 'Thực hành Word định dạng mẫu đơn từ', dueDate: '2026-06-22', assignedCount: 28, submittedCount: 19 },
      { id: 'asgn_02', title: 'Quiz rèn luyện Computing Fundamentals', dueDate: '2026-06-16', assignedCount: 28, submittedCount: 28 },
      { id: 'asgn_03', title: 'Thi thử Module 1: Computing Fundamentals', dueDate: '2026-06-18', assignedCount: 28, submittedCount: 24 },
    ],
  },
  {
    id: 'cls_02',
    name: 'Tin học Đại cương - Nhóm 5',
    code: 'THDC-G5',
    teacherId: 'usr_teacher_01',
    studentCount: 42,
    averageScore: 680,
    students: [
      { id: 'stud_21', name: 'Bùi Việt Hoàng', email: 'hoangbv@st.hust.edu.vn', completedLessons: 6, avgExamScore: 690, predictedPassRate: 64, streakDays: 2, activityStatus: 'active' },
      { id: 'stud_22', name: 'Đỗ Thùy Trang', email: 'trangdt@st.hust.edu.vn', completedLessons: 4, avgExamScore: 580, predictedPassRate: 45, streakDays: 0, activityStatus: 'at_risk' },
    ],
    assignments: [
      { id: 'asgn_11', title: 'Hoàn thành 3 bài học Excel nâng cao', dueDate: '2026-06-25', assignedCount: 42, submittedCount: 12 },
    ],
  },
];
